insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('AT', 'TREE', 72, 0.0, 'APPLE_TREE', 0, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('ATX', 'ANIMAL', 24, 0.0, 'ATTILA_X', 1, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('ATY', 'ANIMAL', 24, 0.0, 'ATTILA_Y', 1, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('BB', 'ANIMAL', 24, 0.0, 'BLACK_BULL', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('BE', 'EXTRACT', 0, 0.0, 'BLACK_EGG', 1, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('BLB', 'ANIMAL', 24, 0.0, 'BILLY_BROWN', 1, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('BP', 'ANIMAL', 24, 0.0, 'BLACK_PUMBA', 1, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('BR', 'ANIMAL', 72, 0.0, 'B_ROOSTER', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('BS', 'ANIMAL', 24, 0.0, 'BLACK_SHINE', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('BSH', 'ANIMAL', 24, 0.0, 'BADSHAW', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('BT', 'TREE', 120, 0.0, 'BANANA_TREE', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('CAS', 'SEED', 72, 0.0, 'CARROT_SEEDS', 0, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('CAF', 'FEED', 0, 0.6, 'CARROT_FEED', 0, 1, 0, 'CAS');
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('COS', 'SEED', 36, 0.0, 'CORN_SEEDS', 0, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('COF', 'FEED', 0, 0.02, 'CORN_FEED', 0, 1, 0, 'COS');
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('COWT', 'ANIMAL', 24, 0.0, 'COW_TRIAL', 0, 0, 1, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('DOR', 'ANIMAL', 24, 0.0, 'DOR', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('DS', 'ANIMAL', 24, 0.0, 'DORPER_SHEEP', 0, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('EGG', 'EXTRACT', 0, 0.0, 'EGG', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('EGR', 'ANIMAL', 24, 0.0, 'EAGGER', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('FCL', 'CROPLAND', 0, 0.0, 'FOUR_THREE_CROP_LAND', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('FRF', 'FEED', 0, 0.025, 'FRUIT_FEED', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('FTR', 'EXTRACT', 0, 0.0, 'FEATHER', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('FUR', 'EXTRACT', 0, 0.0, 'FUR', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('GOATT', 'ANIMAL', 24, 0.0, 'GOAT_TRIAL', 0, 0, 1, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('GR', 'GENERAL', 0, 0.0, 'GREASE', 0, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('HENT', 'ANIMAL', 24, 0.0, 'HEN_TRIAL', 0, 0, 1, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('HGC', 'ANIMAL', 24, 0.0, 'HIGHLAND_COW', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('HH', 'ANIMAL', 24, 0.0, 'HAM_HOCK', 1, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('HHR', 'EXTRACT', 0, 0.0, 'HORSE_HAIR', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('LAKE', 'BUILDING', 24, 0.0, 'LAKE', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('MG', 'ANIMAL', 24, 0.0, 'MOUNTAIN_GOAT', 0, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('MILK', 'EXTRACT', 0, 0.0, 'MILK', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('MP', 'ANIMAL', 24, 0.0, 'MILKY_PEP', 1, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('MUD', 'ANIMAL', 48, 0.0, 'MUD', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('OAK', 'ANIMAL', 24, 0.0, 'OAK', 1, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('OCL', 'CROPLAND', 0, 0.0, 'ONE_ONE_CROP_LAND', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('ORT', 'TREE', 24, 0.0, 'ORANGE_TREE', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('PC', 'ANIMAL', 24, 0.0, 'P1_COW', 0, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('PCG', 'ANIMAL', 24, 0.0, 'PYGMY_CREAM_GOAT', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('PG', 'ANIMAL', 24, 0.0, 'P1_GOAT', 0, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('PH', 'ANIMAL', 24, 0.0, 'P1_HEN', 0, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('PLP', 'ANIMAL', 24, 0.0, 'PLOPPER', 1, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('PMILK', 'EXTRACT', 0, 0.0, 'PRO_MILK', 1, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('POW', 'GENERAL', 0, 0.0, 'POWER', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('PP', 'ANIMAL', 24, 0.0, 'P1_PIG', 0, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('PTRF', 'EXTRACT', 0, 0.0, 'PRO_TRUFFLES', 1, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('RR', 'ANIMAL', 24, 0.0, 'RED_ROOSTER', 0, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('SCL', 'CROPLAND', 0, 0.0, 'SMALL_CROP_LAND', 0, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('SPKY', 'ANIMAL', 24, 0.0, 'SPARKY', 0, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('SPW', 'BUILDING', 24, 0.0, 'SOLAR_PANEL_100W', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('SW', 'BUILDING', 24, 0.0, 'SMALL_WELL', 0, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('TRF', 'EXTRACT', 0, 0.0, 'TRUFFLES', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('WATER', 'GENERAL', 0, 0.0, 'WATER', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('WELL', 'BUILDING', 24, 0.0, 'WELL', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('WG', 'ANIMAL', 24, 0.0, 'WILD_GOAT', 0, 0, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('WOOL', 'EXTRACT', 0, 0.0, 'WOOL', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('WTW', 'BUILDING', 24, 0.0, 'WIND_TURBINE_1KW', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('ZING', 'ANIMAL', 24, 0.0, 'ZING', 0, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('SBF', 'FEED', 0, 0, 'BREED_FEED', 1, 1, 0, NULL);
insert into cb_tools_bot.cb_asset (code, asset_type, duration, grinding_fees, name, pro_asset, tradeable, trial_asset, origin) values ('PMIX', 'FEED', 0, 0, 'PRO_MIX', 1, 1, 0, NULL);

insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (1, 3.0, 'BS', 'COF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (2, 2.0, 'BS', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (3, 3.0, 'GOATT', 'COF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (4, 3.0, 'PCG', 'COF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (5, 1.0, 'PCG', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (6, 3.0, 'PG', 'COF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (7, 2.0, 'PG', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (8, 4.0, 'BB', 'COF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (9, 2.0, 'BB', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (10, 8.0, 'HGC', 'COF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (11, 4.0, 'HGC', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (12, 5.0, 'PC', 'COF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (13, 2.0, 'PC', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (14, 3.0, 'COWT', 'COF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (15, 4.0, 'RR', 'COF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (16, 3.0, 'RR', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (17, 1.0, 'DS', 'COF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (18, 1.0, 'DS', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (19, 5.0, 'MG', 'COF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (20, 3.0, 'MG', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (21, 1.0, 'PH', 'COF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (22, 1.0, 'PH', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (23, 2.0, 'HENT', 'COF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (24, 2.0, 'EGR', 'COF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (25, 1.0, 'EGR', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (26, 2.0, 'BR', 'COF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (27, 2.0, 'BR', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (28, 2.0, 'ATX', 'CAF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (29, 2.0, 'ATX', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (30, 2.0, 'ATY', 'CAF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (31, 2.0, 'ATY', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (32, 6.0, 'ZING', 'COF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (33, 3.0, 'ZING', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (34, 6.0, 'BSH', 'COF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (35, 3.0, 'BSH', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (36, 3.0, 'MUD', 'COF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (37, 1.0, 'MUD', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (38, 2.0, 'BP', 'CAF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (39, 4.0, 'BP', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (40, 1.0, 'HH', 'CAF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (41, 2.0, 'HH', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (42, 3.0, 'PLP', 'CAF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (43, 6.0, 'PLP', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (44, 6.0, 'SPKY', 'COF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (45, 3.0, 'SPKY', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (46, 4.0, 'DOR', 'COF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (47, 2.0, 'DOR', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (48, 1.0, 'BLB', 'CAF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (49, 2.0, 'BLB', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (50, 3.0, 'MP', 'CAF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (51, 6.0, 'MP', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (52, 2.0, 'OAK', 'CAF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (53, 4.0, 'OAK', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (54, 5.0, 'WG', 'COF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (55, 2.0, 'WG', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (56, 4.0, 'PP', 'COF');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (57, 3.0, 'PP', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (58, 0.3, 'WTW', 'GR');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (59, 0.03, 'SPW', 'GR');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (60, 0.36, 'LAKE', 'POW');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (61, 0.24, 'WELL', 'POW');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (62, 0.12, 'SW', 'POW');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (63, 1.0, 'SCL', 'CAS');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (64, 1.0, 'SCL', 'COS');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (65, 1.0, 'SCL', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (66, 1.0, 'OCL', 'CAS');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (67, 1.0, 'OCL', 'COS');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (68, 1.0, 'OCL', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (69, 12.0, 'FCL', 'CAS');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (70, 12.0, 'FCL', 'COS');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (71, 12.0, 'FCL', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (72, 5.0, 'AT', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (73, 5.0, 'BT', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (74, 10.0, 'ORT', 'WATER');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (75, 0.1, 'CAF', 'POW');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (76, 0.01, 'COF', 'POW');
insert into cb_tools_bot.cb_requirement (id, amount, origin, target) values (77, 0.015, 'FRF', 'POW');

insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (1, 3.0, 'BS', 'MILK');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (2, 1.0, 'GOATT', 'MILK');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (3, 3.0, 'PCG', 'MILK');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (4, 3.0, 'PG', 'MILK');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (5, 2.0, 'BB', 'FUR');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (6, 12.0, 'HGC', 'MILK');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (7, 4.0, 'PC', 'MILK');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (8, 1.0, 'COWT', 'MILK');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (9, 1.0, 'RR', 'FTR');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (10, 3.0, 'DS', 'WOOL');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (11, 2.0, 'MG', 'FUR');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (12, 4.0, 'PH', 'EGG');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (13, 1.0, 'HENT', 'EGG');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (14, 4.0, 'EGR', 'EGG');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (15, 2.0, 'BR', 'FTR');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (16, 2.0, 'ATX', 'BE');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (17, 2.0, 'ATY', 'BE');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (18, 2.0, 'ZING', 'HHR');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (19, 2.0, 'BSH', 'HHR');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (20, 4.0, 'MUD', 'TRF');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (21, 2.0, 'BP', 'PTRF');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (22, 1.0, 'HH', 'PTRF');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (23, 3.0, 'PLP', 'PTRF');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (24, 4.0, 'SPKY', 'TRF');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (25, 6.0, 'DOR', 'WOOL');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (26, 1.0, 'BLB', 'PMILK');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (27, 3.0, 'MP', 'PMILK');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (28, 2.0, 'OAK', 'PMILK');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (29, 2.0, 'WG', 'FUR');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (30, 1.0, 'PP', 'TRF');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (31, 30.0, 'WTW', 'POW');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (32, 3.0, 'SPW', 'POW');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (33, 36.0, 'LAKE', 'WATER');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (34, 24.0, 'WELL', 'WATER');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (35, 12.0, 'SW', 'WATER');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (36, 3.0, 'SCL', 'CAF');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (37, 6.0, 'SCL', 'COF');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (38, 5.0, 'OCL', 'CAF');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (39, 12.0, 'OCL', 'COF');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (40, 60.0, 'FCL', 'CAF');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (41, 144.0, 'FCL', 'COF');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (42, 3.0, 'AT', 'FRF');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (43, 5.0, 'BT', 'FRF');
insert into cb_tools_bot.cb_extract (id, amount, origin, target) values (44, 2.0, 'ORT', 'FRF');

insert into cb_tools_bot.cb_currency (code, name) values ('CBX', 'CropBytes Token');
insert into cb_tools_bot.cb_currency (code, name) values ('TRX', 'Tron');
insert into cb_tools_bot.cb_currency (code, name) values ('USDT', 'USDT');

insert into cb_tools_bot.cb_market_quote (id, avg_price, price, price_change, timestamp, volume, asset, currency) values (999991, 0.1, 0.1, 0, '2199-12-31', 0, 'COS', 'CBX');
insert into cb_tools_bot.cb_market_quote (id, avg_price, price, price_change, timestamp, volume, asset, currency) values (999992, 2, 2, 0, '2199-12-31', 0, 'CAS', 'CBX');
insert into cb_tools_bot.cb_market_quote (id, avg_price, price, price_change, timestamp, volume, asset, currency) values (999993, 10, 10, 0, '2199-12-31', 0, 'GR', 'CBX');

insert into cb_tools_bot.tg_bot_command (command, executor, disabled, development, admin) values ('/start', 'net.cattweasel.cropbytes.telegram.cmd.HelpCommand', 0, 0, 0);
insert into cb_tools_bot.tg_bot_command (command, executor, disabled, development, admin) values ('/help', 'net.cattweasel.cropbytes.telegram.cmd.HelpCommand', 0, 0, 0);
insert into cb_tools_bot.tg_bot_command (command, executor, disabled, development, admin) values ('/assets', 'net.cattweasel.cropbytes.telegram.cmd.AssetsCommand', 0, 0, 0);
insert into cb_tools_bot.tg_bot_command (command, executor, disabled, development, admin) values ('/quotes', 'net.cattweasel.cropbytes.telegram.cmd.QuotesCommand', 0, 0, 0);
insert into cb_tools_bot.tg_bot_command (command, executor, disabled, development, admin) values ('/profit', 'net.cattweasel.cropbytes.telegram.cmd.ProfitCommand', 0, 0, 0);
insert into cb_tools_bot.tg_bot_command (command, executor, disabled, development, admin) values ('/packs', 'net.cattweasel.cropbytes.telegram.cmd.PacksCommand', 0, 0, 0);
insert into cb_tools_bot.tg_bot_command (command, executor, disabled, development, admin) values ('/alerts', 'net.cattweasel.cropbytes.telegram.cmd.AlertsCommand', 0, 0, 0);
insert into cb_tools_bot.tg_bot_command (command, executor, disabled, development, admin) values ('/farms', 'net.cattweasel.cropbytes.telegram.cmd.FarmsCommand', 0, 0, 0);
insert into cb_tools_bot.tg_bot_command (command, executor, disabled, development, admin) values ('/broadcast', 'net.cattweasel.cropbytes.telegram.cmd.BroadcastCommand', 0, 0, 1);
insert into cb_tools_bot.tg_bot_command (command, executor, disabled, development, admin) values ('/settings', 'net.cattweasel.cropbytes.telegram.cmd.SettingsCommand', 0, 0, 0);

insert into cb_tools_bot.tg_user (user_id, last_seen, username, admin, broadcast_disabled, sleep_mode) values (591508791, '01.01.2000', 'cattweasel', 1, 0, 0);